name: E2E Container Experiment

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # container:
    #   image: cypress/browsers:latest
    #   options: --user 1001
    services:
      layer8:
        image: stravid87/layer8-server:latest
        ports: 
          - 5001:5001
      wgp:
        image: stravid87/wgp_mock_backend:latest
        ports:
          - 8000:8000
    steps:
      - run: sudo apt-get install curl
      - run: curl http://127.0.0.1:8000/healthcheck && echo ""
      # - run: curl http://layer8:5001
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     component: true
      #     browser: chrome
      #     wait-on: 'http://localhost:8000, http://localhost:5001'
      #     wait-on-timeout: 30
          
      # - name: run testing
      #   run: npm test:e2e:dev
      - name: Echo Test
        run: echo "nice..."



  # load-l8-containers:
  #   runs-on: ubuntu-latest
  #   container: node:lts-alpine # The container this job will run in?
