name: E2E Container Experiment

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome
      - name: run testing
        run: npm test:e2e:dev
      - name: Echo Test
        run: echo "nice..."

  # services:
  #   runs-on: ubuntu-latest
  #   layer8:
  #     image: stravid87/layer8-server:latest
  #   wgp:
  #     image: stravid87/wgp_mock_backend:latest

  # load-l8-containers:
  #   runs-on: ubuntu-latest
  #   container: node:lts-alpine # The container this job will run in?
